In [1]:
"""
データセットのタイトル、説明、データの緯度経度から、候補となるgeonames地名を出力する動作デモ
"""

'\nデータセットのタイトル、説明、データの緯度経度から、候補となるgeonames地名を出力する動作デモ\n'

In [2]:
import extract_spatial
import pandas as pd

In [3]:
from IPython.display import display
def evaluation(index, title,notes,filepath,method="hybrid"):
    print("==========================================")
    print("index: ",index)
    print("[input information]")
    print("- title: ",title)
    print("- notes: ",notes)
    print("- filepath: ",filepath)
    print("\n")

    print("[Estimation Result]")
    lngArray,latArray = extract_spatial.extract_lnglatArray_csv(filepath=filepath)
    df = extract_spatial.extractSpatialDf(title=title, notes=notes, lngArray=lngArray,latArray=latArray,method=method)
    display(df)
    print("\n")

In [4]:

df_test = pd.read_csv('evaluation_input.csv', header=0)
#df_test = df_test.tail()
print("[評価で用いる入力データ一覧]")
display(df_test)
print("\n")

for index, row in df_test.iterrows():
    evaluation(index=index,title=row.title,notes=row.notes,filepath=row.filepath,method="hybrid")

[評価で用いる入力データ一覧]

,site,title,notes,filepath,dataset_url,memo
0,G空間,"""142158_神奈川県_海老名市_公園・スポーツ施設""","""公園・スポーツ施設のデータです。神奈川県海老名市のオープンデータです""",https://www.geospatial.jp/ckan/dataset/015c634...,NaN,NaN
1,G空間,"""松江駅構内人流センサデータ 2020年6月""","""松江駅構内17箇所に設置した人流センサのデータです""",https://www.geospatial.jp/ckan/dataset/962840f...,NaN,NaN
2,G空間,"""142131_神奈川県_大和市_農園・農産物""","""神奈川県大和市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/6b18838...,NaN,NaN
3,G空間,"""131202_東京都_練馬区_避難施設""","""避難所、避難場所等のデータです。東京都練馬区のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/ddbe667...,NaN,NaN
4,G空間,"""131041_東京都_新宿区_公衆無線LAN""","""公衆無線LANやWiFi SPOTのデータです。東京都新宿区のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/aeb988e...,NaN,NaN
5,G空間,"""122203_千葉県_流山市_災害用井戸設置場所""","""流山市の災害用井戸設置場所です。千葉県流山市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/43b0989...,NaN,NaN
6,G空間,"""052035_秋田県_横手市_消防水利""","""消火栓、防火水槽等のデータです。秋田県横手市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/fae02ea...,NaN,NaN
7,G空間,"""33100_岡山県_岡山市_防災情報""","""液状化マップ、地震危険度マップ、洪水時の浸水深、津波時の浸水深（堤防なし）、ため池浸水想定...",https://www.geospatial.jp/ckan/dataset/92f2a03...,NaN,NaN
8,G空間,"""142042_神奈川県_鎌倉市_消防水利""","""消火栓、防火水槽等のデータです。神奈川県鎌倉市のオープンデータです""",https://www.geospatial.jp/ckan/dataset/1797a2c...,https://www.geospatial.jp/ckan/dataset/14204-003,NaN
9,G空間,"""132136_東京都_東村山市_医療施設""","""医療施設のデータです。\n東京都東村山市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/04e71bf...,https://www.geospatial.jp/ckan/dataset/13213-010,NaN
10,G空間,"""132098_東京都_町田市_文化・コミュニティ施設""","""文化・コミュニティのデータです。\n東京都町田市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/416cd8e...,https://www.geospatial.jp/ckan/dataset/13209-013,緯度、経度の値はあるが、測地系が違う
11,G空間,"""131199_東京都_板橋区_観光情報""","""観光施設やイベント等のデータです。\n東京都板橋区のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/2b61bcf...,NaN,NaN
12,G空間,"""131237_東京都_江戸川区_土のうステーション""","""土のうステーションのデータです。\n東京都江戸川区のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/9a5b716...,NaN,NaN
13,G空間,"""092088_栃木県_小山市_公衆トイレ""","""公衆トイレや公共トイレのデータです。\n栃木県小山市のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/8517fad...,NaN,NaN
14,G空間,"""090000_栃木県_避難施設""","""避難所、避難場所等のデータです。\n栃木県のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/c2e3cfc...,NaN,列名が未対応
15,G空間,"""114081_埼玉県_寄居町_観光地情報""","""観光地情報のデータです。\n埼玉県寄居町のオープンデータです。""",https://www.geospatial.jp/ckan/dataset/f4ec070...,NaN,列名が未対応
16,G空間,"""高砂市ベストスポット2018""","""2018年に高砂市役所が発表した、市民投票によるベストスポットの位置情報です。 推奨データ...",https://www.geospatial.jp/ckan/dataset/2dc3b2b...,NaN,NaN
17,G空間,"""37_香川県_雨量観測所""","""雨量データを公表している雨量観測所の所在地一覧です""",NaN,NaN,CSV形式データなし
18,東京都,"""避難所""","""【品川区】 災害時等の避難所の位置情報""",http://www.city.shinagawa.tokyo.jp/ct/other000...,NaN,元データに経度の値に緯度の値が入っているのがある
19,東京都,"""区内の橋梁一覧""","""区内の橋梁の名称や読み方、所在地、緯度、経度、管理者、橋下状況などを掲載しています。""",https://www.city.chuo.lg.jp/kusei/statisticald...,NaN,キーワード記載なし
20,東京都,"""東京都内のスポーツ施設一覧""","""【東京都オリンピック・パラリンピック準備局】""",http://www.opendata.metro.tokyo.jp/2018appcon/...,NaN,NaN
21,東京都,"""【位置情報】公衆無線LANアクセスポイント一覧""","""公衆無線LANアクセスポイントの一覧データです。""",https://www.city.mitaka.lg.jp/c_service/085/at...,NaN,NaN
22,東京都,"""観光施設一覧""","""【西東京市】西東京市内の観光施設の一覧です。内閣官房情報通信技術（IT）総合戦略室が平成2...",http://www.city.nishitokyo.lg.jp/opendata/1322...,NaN,NaN
23,東京都,"""文化財一覧""","""【東京都教育庁】東京都指定文化財の一覧です。現在は、一般公開されており、所有者・管理者の承...",http://www.opendata.metro.tokyo.jp/suisyoudata...,https://catalog.data.metro.tokyo.lg.jp/dataset...,経度のデータの値がおかしいたため、Bbox算出値がおかしくなる。
24,東京都,"""東京都イベント一覧""","""【東京都総務局】東京都が主催者等であるイベント情報の一覧です。 内閣官房情報通信技術（IT...",http://www.opendata.metro.tokyo.jp/suisyoudata...,NaN,NaN
25,福岡,"""福岡市 避難場所・避難所（共通フォーマット）""","""福岡市の避難場所・避難所を，福岡市，北九州市，久留米市の３市で共通化したフォーマットにした...",https://ckan.open-governmentdata.org/dataset/b...,NaN,NaN
26,福岡,"""北九州市 避難場所・避難所（共通フォーマット）""","""北九州市の避難場所・避難所を、北九州市、福岡市、久留米市の３市で共通化したフォーマットにし...",https://ckan.open-governmentdata.org/dataset/0...,NaN,NaN
27,静岡,"""農産物直売所""","""市内のファーマーズマーケット開催情報です。データ形式 lodでも公開しています。http:...",https://ckan.pref.shizuoka.jp/dataset/35fea25e...,https://ckan.pref.shizuoka.jp/dataset/91331960...,NaN
28,datagojp,"""パブリックタグ情報""","""国土地理院に登録されたWi-Fiやビーコンなど位置特定に利用可能な機器の設置位置などの属性...",https://ucopendb.gsi.go.jp/ucode/ptisi_opendat...,https://www.data.go.jp/data/dataset/mlit_20160...,NaN
29,datagojp,"""気象予報_天気予報・台風の資料""","""過去の天気図や台風資料、予報の精度検証結果などの天気予報・台風の分析・統計資料""",https://www.data.jma.go.jp/fcd/yoho/typhoon/po...,NaN,NaN
30,その他,NaN,NaN,https://koukita.github.io/hokkaido_od_geodatab...,NaN,NaN
31,その他,国分寺市にある避難所の位置情報データ,国分寺市にある避難所の位置情報データ,NaN,NaN,自分で適当に作成したダミーデータ

==========================================
index:  0
[input information]
- title:  "142158_神奈川県_海老名市_公園・スポーツ施設"
- notes:  "公園・スポーツ施設のデータです。神奈川県海老名市のオープンデータです"
- filepath:  https://www.geospatial.jp/ckan/dataset/015c6346-97a3-4e63-b357-135b32c4d5b7/resource/f9eae9a9-fc03-4992-b6b7-22b180db6a2f/download/14215parksport.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,7470889,海老名市,A,35.43762,139.39307,神奈川県,海老名市,46.270805,keyword&Bbox,NaN,0.0,3
1,1860291,神奈川県,A,35.41667,139.33333,神奈川県,,53.515060,keyword,神奈川県,2.0,2
2,6822128,海老名,P,35.38121,139.39651,神奈川県,高座郡,42.533043,keyword,海老名市,1.0,2
3,11612543,海老名,P,35.43417,139.39419,神奈川県,海老名市,15.170536,keyword,海老名,1.0,1
4,1864864,綾瀬市,A,35.43995,139.43089,神奈川県,綾瀬市,46.270805,Bbox,NaN,0.0,1
5,10427225,城山公園,L,35.43742,139.41897,神奈川県,綾瀬市,34.703102,Bbox,NaN,0.0,1
6,10427407,光綾公園,L,35.44711,139.43191,神奈川県,綾瀬市,34.703102,Bbox,NaN,0.0,1
7,1907236,中新田,P,35.43739,139.38299,神奈川県,海老名市,28.919254,Bbox,NaN,0.0,1
8,1907240,用田,P,35.40822,139.41861,神奈川県,藤沢市,28.919254,Bbox,NaN,0.0,1
9,10426305,大谷,P,35.43798,139.39067,神奈川県,海老名市,28.919254,Bbox,NaN,0.0,1
10,10426310,浜田町,P,35.44085,139.40427,神奈川県,海老名市,28.919254,Bbox,NaN,0.0,1
11,10426311,勝瀬,P,35.44588,139.39723,神奈川県,海老名市,28.919254,Bbox,NaN,0.0,1
12,10426314,中央,P,35.45106,139.39324,神奈川県,海老名市,28.919254,Bbox,NaN,0.0,1

==========================================
index:  1
[input information]
- title:  "松江駅構内人流センサデータ　2020年6月"
- notes:  "松江駅構内17箇所に設置した人流センサのデータです"
- filepath:  https://www.geospatial.jp/ckan/dataset/962840f7-ebee-4e92-9004-d9b9ebeaf6f3/resource/a7ab42ee-8ce2-41de-9e4d-b57615518a6c/download/20200601.csv


[Estimation Result]
Error: 緯度、経度の列がありません

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,7561735,まつええき,S,35.46409,133.06396,島根県,松江市,17.470661,keyword,松江駅,2

==========================================
index:  2
[input information]
- title:  "142131_神奈川県_大和市_農園・農産物"
- notes:  "神奈川県大和市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/6b188386-3a8c-4ad2-9f93-171fc99bfb25/resource/9f824f08-15a6-44ce-a160-b8ef16d6f9f2/download/000121491.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1848595,大和市,A,35.46934,139.46165,神奈川県,大和市,46.270805,keyword&Bbox,NaN,0.0,3
1,11611478,大和,P,35.47276,139.45101,神奈川県,大和市,29.166679,keyword&Bbox,大和,1.0,2
2,1860291,神奈川県,A,35.41667,139.33333,神奈川県,,53.515060,keyword,神奈川県,2.0,2
3,9815255,産物,P,40.21707,140.09716,秋田県,能代市,31.137297,keyword,産物,1.0,1
4,8312334,大和,P,40.60048,141.25385,青森県,十和田市,29.166679,keyword,大和,1.0,1
5,11077908,やまと,P,35.37907,139.9306,千葉県,木更津市,29.166679,keyword,大和,1.0,1
6,11525877,ヤマト,P,42.03191,143.13568,北海道,幌泉郡,29.166679,keyword,大和,1.0,1
7,11672108,大和,P,43.88292,143.87197,北海道,北見市,29.166679,keyword,大和,1.0,1
8,9280822,大和,P,34.86017,135.57345,大阪府,高槻市,26.739021,keyword,大和,1.0,1
9,11243899,大鶴,P,33.12411,131.10743,熊本県,阿蘇郡,23.900955,keyword,大和,1.0,1
10,11274218,大和,P,32.97719,130.46812,熊本県,荒尾市,23.900955,keyword,大和,1.0,1
11,11811505,大和,P,37.08829,138.25573,新潟県,上越市,14.788544,keyword,大和,1.0,1
12,1857144,南林間,P,35.49527,139.44279,神奈川県,大和市,69.406204,Bbox,NaN,0.0,1
13,6300402,Atsugi United States Naval Air Station,S,35.45461,139.45017,神奈川県,綾瀬市,57.838509,Bbox,NaN,0.0,1
14,1848598,大和南,P,35.46644,139.4653,神奈川県,大和市,34.703102,Bbox,NaN,0.0,1
15,1855148,西鶴間,P,35.48646,139.4453,神奈川県,大和市,28.919254,Bbox,NaN,0.0,1
16,10434112,目黒町,P,35.49773,139.46941,神奈川県,横浜市,28.919254,Bbox,NaN,0.0,1
17,10434113,五貫目町,P,35.5002,139.47213,神奈川県,横浜市,28.919254,Bbox,NaN,0.0,1
18,1852581,Shibuya-machi,A,35.43333,139.46667,,,28.628599,Bbox,NaN,0.0,1
19,1853058,Sakurakabu,P,35.45,139.46667,神奈川県,大和市,28.628599,Bbox,NaN,0.0,1

==========================================
index:  3
[input information]
- title:  "131202_東京都_練馬区_避難施設"
- notes:  "避難所、避難場所等のデータです。東京都練馬区のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/ddbe6679-257f-40be-a78e-318faf4bf7e1/resource/50237252-7488-4972-b46d-37614d414683/download/hinankyoten1.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1855502,練馬区,A,35.73551,139.65168,東京都,練馬区,46.588428,keyword&Bbox,練馬区,2.0,3
1,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
2,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
3,1851898,白子,P,35.77507,139.62237,埼玉県,和光市,34.703102,Bbox,NaN,0.0,1
4,1864231,江古田,P,35.72552,139.66516,東京都,中野区,34.703102,Bbox,NaN,0.0,1
5,8573526,沼袋,P,35.72174,139.66625,東京都,中野区,34.703102,Bbox,NaN,0.0,1
6,11010246,城北中央公園,L,35.75625,139.6731,東京都,練馬区,34.703102,Bbox,NaN,0.0,1
7,11011087,大泉中央公園,L,35.77496,139.59829,東京都,練馬区,34.703102,Bbox,NaN,0.0,1
8,10865994,哲学堂,L,35.72267,139.67433,東京都,中野区,34.703102,Bbox,NaN,0.0,1
9,10866163,石神井公園,L,35.73812,139.60261,東京都,練馬区,34.703102,Bbox,NaN,0.0,1
10,8572717,栄,P,35.77439,139.57933,埼玉県,新座市,28.919254,Bbox,NaN,0.0,1
11,8572879,おおいずみがくえんちょう,P,35.7653,139.58877,東京都,練馬区,28.919254,Bbox,NaN,0.0,1

==========================================
index:  4
[input information]
- title:  "131041_東京都_新宿区_公衆無線LAN"
- notes:  "公衆無線LANやWiFi SPOTのデータです。東京都新宿区のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/aeb988eb-ef78-4625-9f83-5ca49719d209/resource/53c3fdf6-827e-4e57-9176-260739d3af8d/download/717.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1852083,新宿区,A,35.69384,139.70355,東京都,新宿区,38.745346,keyword&Bbox,新宿区,2.0,3
1,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
2,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
3,7438386,新宿区役所,S,35.69389,139.70361,東京都,新宿区,23.135403,Bbox,NaN,0.0,1
4,8534744,シンジュクニシグチエキ,S,35.69316,139.69916,東京都,新宿区,23.135403,Bbox,NaN,0.0,1
5,8534745,しんじゅくさんちょうめえき,S,35.69118,139.70421,東京都,新宿区,23.135403,Bbox,NaN,0.0,1
6,12022150,Shinjuku Omoide Yokochō,R,35.69312,139.69955,東京都,新宿区,11.567701,Bbox,NaN,0.0,1
7,11994419,Golden Gai,R,35.69403,139.70468,東京都,新宿区,11.567701,Bbox,NaN,0.0,1
8,10127327,Ibis Tokyo Shinjuku (D),S,35.69392,139.69831,東京都,新宿区,5.783851,Bbox,NaN,0.0,1
9,7627149,Star Hotel Tokyo,S,35.694,139.69832,東京都,新宿区,5.783851,Bbox,NaN,0.0,1
10,7627158,Best Western Shinjuku ASTINA Hotel Tokyo,S,35.69445,139.70432,東京都,新宿区,5.783851,Bbox,NaN,0.0,1
11,10115769,Central Hotel Tokyo,S,35.6904,139.70244,東京都,新宿区,5.783851,Bbox,NaN,0.0,1

==========================================
index:  5
[input information]
- title:  "122203_千葉県_流山市_災害用井戸設置場所"
- notes:  "流山市の災害用井戸設置場所です。千葉県流山市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/43b0989d-6683-4e01-99b9-b57c10e3dbbd/resource/f6322982-1415-4b76-9053-e88bb6143b7b/download/saigaiyouido2.csv


[Estimation Result]
Error: 緯度、経度の列がありません

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,2113014,千葉県,A,35.60506,140.12333,千葉県,,62.039558,keyword,千葉県,2
1,1856184,流山,P,35.8563,139.90266,千葉県,流山,53.595840,keyword,流山,2
2,8383629,流山,T,40.90538,140.9249,青森県,東津軽郡,32.328560,keyword,流山,2
3,1856183,流山,A,35.85631,139.90266,千葉県,流山,30.626194,keyword,流山,2
4,9629441,井戸,P,34.31737,135.97538,奈良県,吉野郡,29.118065,keyword,井戸,2
5,11777391,井戸,P,34.26559,134.15641,香川県,木田郡,16.284527,keyword,井戸,2

==========================================
index:  6
[input information]
- title:  "052035_秋田県_横手市_消防水利"
- notes:  "消火栓、防火水槽等のデータです。秋田県横手市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/fae02eaf-648a-4084-86e5-1460d979a947/resource/3219d9fd-2468-4d60-9371-5ebd963a7403/download/000072364.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,2110504,横手,A,39.28369,140.54432,秋田県,横手市,46.270805,keyword&Bbox,NaN,0.0,3
1,2110506,横手町,P,39.31691,140.55034,秋田県,横手市,46.270805,keyword&Bbox,NaN,0.0,2
2,2113124,秋田県,A,39.75,140.4,秋田県,,57.899479,keyword,秋田県,2.0,2
3,8505976,ヨコテ,P,40.74575,140.72631,青森県,青森市,31.305401,keyword,横手,1.0,1
4,11209534,横手,P,32.80138,130.68847,熊本県,熊本市,31.305401,keyword,横手,1.0,1
5,9890420,横手,P,33.15965,130.13781,佐賀県,杵島郡,29.213032,keyword,横手,1.0,1
6,9888311,横手,P,33.54785,130.43689,福岡県,福岡市,29.213032,keyword,横手,1.0,1
7,10256621,横手,P,32.29671,130.76732,熊本県,球磨郡,25.739105,keyword,横手,1.0,1
8,11192336,横手,P,32.56542,130.8574,熊本県,八代市,25.739105,keyword,横手,1.0,1
9,11171622,ヨコテ,P,35.13667,140.09345,千葉県,鴨川市,25.739105,keyword,横手,1.0,1
10,10413148,横手,P,35.40105,139.19373,神奈川県,秦野市,20.172810,keyword,横手,1.0,1
11,2112729,Hiraka-gun,A,39.25,140.61667,,Hiraka-gun,46.270805,Bbox,NaN,0.0,1
12,2112453,角間川町,P,39.4,140.48333,秋田県,大仙市,34.703102,Bbox,NaN,0.0,1
13,2110730,通醍醐,P,39.24287,140.53268,秋田県,横手市,34.703102,Bbox,NaN,0.0,1
14,2111483,大日向山,T,39.20925,140.66507,秋田県,横手市,34.703102,Bbox,NaN,0.0,1
15,2110533,Yasawagi,L,39.36667,140.35,,,32.718399,Bbox,NaN,0.0,1
16,2112485,Jūmonji-machi,A,39.21667,140.51667,,,28.919254,Bbox,NaN,0.0,1
17,2112486,十文字町,P,39.21667,140.51667,秋田県,横手市,28.919254,Bbox,NaN,0.0,1
18,2112579,石成,P,39.24608,140.53475,秋田県,横手市,28.919254,Bbox,NaN,0.0,1

==========================================
index:  7
[input information]
- title:  "33100_岡山県_岡山市_防災情報"
- notes:  "液状化マップ、地震危険度マップ、洪水時の浸水深、津波時の浸水深（堤防なし）、ため池浸水想定マップ、ゆれやすさマップのデータです。岡山県岡山市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/92f2a033-e2c7-4bdd-8eee-456d5642be77/resource/a4da9bea-c9fb-4452-abfd-b3223d6d2fbb/download/tameike.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1854381,岡山県,A,34.90204,133.81018,岡山県,,54.196476,keyword&Bbox,岡山県,2.0,4
1,1854383,岡山,P,34.65,133.93333,岡山県,岡山市,92.541611,keyword&Bbox,NaN,0.0,3
2,1854380,おかやまし,A,34.71251,133.92329,岡山県,岡山市,38.446518,keyword,岡山市,1.0,2
3,8721301,水深,P,35.18792,139.65083,神奈川県,三浦市,26.005680,keyword,水深,2.0,2
4,11031583,水深,P,35.87575,139.69099,埼玉県,さいたま市,26.005680,keyword,水深,2.0,2
5,11056810,みずがみ,P,35.16314,139.65696,神奈川県,三浦市,26.005680,keyword,水深,2.0,2
6,10475432,水神,P,35.15455,138.62954,静岡県,富士市,20.393709,keyword,水深,2.0,2
7,1849733,津波,P,26.65753,128.09412,沖縄県,国頭郡,41.192268,keyword,津波,1.0,1
8,9280887,岡山,P,34.74553,135.64048,大阪府,四條畷市,28.806580,keyword,岡山,1.0,1
9,11402953,おかやま,P,32.15525,130.38652,熊本県,水俣市,25.431496,keyword,岡山,1.0,1
10,1858311,倉敷市,P,34.58333,133.76667,岡山県,倉敷市,80.973907,Bbox,NaN,0.0,1
11,6300372,岡山空港,S,34.75694,133.85528,岡山県,岡山市,57.838509,Bbox,NaN,0.0,1
12,1858309,倉敷,A,34.55466,133.74826,岡山県,倉敷市,46.270805,Bbox,NaN,0.0,1
13,1858769,後楽園,L,34.66784,133.93609,岡山県,岡山市,46.270805,Bbox,NaN,0.0,1
14,1858998,児島湖,H,34.57918,133.93854,岡山県,,46.270805,Bbox,NaN,0.0,1
15,1849672,つくぼぐん,A,34.60857,133.82241,岡山県,都窪郡,46.270805,Bbox,NaN,0.0,1
16,1850741,玉野市,A,34.52507,133.93769,岡山県,玉野市,46.270805,Bbox,NaN,0.0,1
17,1851606,総社,P,34.67534,133.75091,岡山県,総社市,46.270805,Bbox,NaN,0.0,1

==========================================
index:  8
[input information]
- title:  "142042_神奈川県_鎌倉市_消防水利"
- notes:  "消火栓、防火水槽等のデータです。神奈川県鎌倉市のオープンデータです"
- filepath:  https://www.geospatial.jp/ckan/dataset/1797a2cd-1843-402d-97a0-41509cee7e72/resource/5145c7d9-3fa2-4e25-869a-e4a62e4e0391/download/boukasuisou.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1860672,鎌倉,P,35.30889,139.55028,神奈川県,鎌倉市,80.973907,keyword&Bbox,NaN,0.0,3
1,1860670,鎌倉市,A,35.33,139.53798,神奈川県,鎌倉市,46.270805,keyword&Bbox,NaN,0.0,3
2,1860291,神奈川県,A,35.41667,139.33333,神奈川県,,53.515060,keyword,神奈川県,2.0,2
3,10920028,鎌倉,P,35.74575,139.87939,東京都,葛飾区,35.770088,keyword,鎌倉,1.0,1
4,9290081,鎌倉,P,34.98154,135.33169,兵庫県,川辺郡,30.088615,keyword,鎌倉,1.0,1
5,8726157,カマクラズシハイランド,L,35.31055,139.57409,神奈川県,,40.486954,Bbox,NaN,0.0,1
6,8726601,鎌倉中央公園,L,35.33448,139.53068,神奈川県,鎌倉市,40.486954,Bbox,NaN,0.0,1
7,11058869,ふえだこうえん,L,35.32288,139.52102,神奈川県,鎌倉市,40.486954,Bbox,NaN,0.0,1
8,1858598,小動岬,T,35.30609,139.49371,神奈川県,鎌倉市,34.703102,Bbox,NaN,0.0,1
9,1858727,腰越,P,35.30935,139.49477,神奈川県,鎌倉市,34.703102,Bbox,NaN,0.0,1
10,1854713,オオフナ,P,35.3491,139.54062,神奈川県,鎌倉市,34.703102,Bbox,NaN,0.0,1
11,8726166,ザイモクザ,P,35.30891,139.55125,神奈川県,鎌倉市,34.703102,Bbox,NaN,0.0,1
12,8726204,キヌバリヤマ,T,35.31759,139.56714,神奈川県,鎌倉市,34.703102,Bbox,NaN,0.0,1

==========================================
index:  9
[input information]
- title:  "132136_東京都_東村山市_医療施設"
- notes:  "医療施設のデータです。
東京都東村山市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/04e71bff-43be-4e3d-87b1-92b33a87d8b7/resource/6e6a84d5-7aa2-471e-a351-dd6f81950997/download/13213kyukyu.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,7279570,東村山市,P,35.75459,139.46852,東京都,東村山市,69.406204,keyword&Bbox,NaN,0.0,3
1,1862768,東村山市,A,35.75529,139.46972,東京都,東村山市,46.270805,keyword&Bbox,NaN,0.0,3
2,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
3,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
4,6822136,東大和,P,35.76298,139.44575,東京都,東村山市,26.917299,keyword,東村山,1.0,1
5,1862769,Higashi-murayama-machi,A,35.75,139.46667,東京都,,46.270805,Bbox,NaN,0.0,1
6,7551884,久米川駅,S,35.74952,139.47269,東京都,東村山市,23.135403,Bbox,NaN,0.0,1
7,7551864,東村山駅,S,35.75997,139.46586,東京都,東村山市,17.351551,Bbox,NaN,0.0,1
8,7551880,八坂駅,S,35.74489,139.46775,東京都,東村山市,17.351551,Bbox,NaN,0.0,1
9,7424845,ひがしむらやましやくしょ,S,35.75472,139.46861,東京都,東村山市,17.351551,Bbox,NaN,0.0,1
10,11807472,柳窪,P,35.75261,139.49049,東京都,東村山市,11.567701,Bbox,NaN,0.0,1

==========================================
index:  10
[input information]
- title:  "132098_東京都_町田市_文化・コミュニティ施設"
- notes:  "文化・コミュニティのデータです。
東京都町田市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/416cd8eb-156a-4bd0-b828-fe567e1ba0ae/resource/bb1a0ecf-ea17-44d8-b351-0837e7459aa4/download/13209toshokan.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1850147.0,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
1,1857871.0,町田市,P,35.54028,139.45083,東京都,町田市,73.478928,keyword,町田市,1.0,2
2,1850144.0,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
3,1857869.0,町田市,A,35.57626,139.42998,東京都,町田市,38.446518,keyword,町田市,1.0,2
4,11710429.0,ぶんか,P,43.09699,143.22329,北海道,河東郡,24.811647,keyword,文化,2.0,2
5,11790371.0,文花,P,35.70946,139.821,東京都,墨田区,19.400734,keyword,文化,2.0,2
6,10922476.0,文化,H,35.70927,139.82379,東京都,,13.989820,keyword,文化,2.0,2
7,1864520.0,町田,P,34.86581,134.64143,兵庫県,姫路市,34.779327,keyword,町田,1.0,1
8,8411691.0,マチダ,P,40.63818,140.46104,青森県,弘前市,31.305401,keyword,町田,1.0,1
9,11138973.0,町田,P,35.48562,140.08497,千葉県,市原市,31.305401,keyword,町田,1.0,1
10,1857872.0,町田,P,34.25195,134.30199,香川県,東かがわ市,29.213032,keyword,町田,1.0,1
11,1857873.0,町田,P,33.21667,131.18333,大分県,玖珠郡,29.213032,keyword,町田,1.0,1
12,9889162.0,町田,P,33.43979,129.96769,佐賀県,唐津市,29.213032,keyword,町田,1.0,1
13,10731432.0,町田,P,35.19401,138.91952,静岡県,裾野市,20.172810,keyword,町田,1.0,1

==========================================
index:  11
[input information]
- title:  "131199_東京都_板橋区_観光情報"
- notes:  "観光施設やイベント等のデータです。
東京都板橋区のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/2b61bcf8-64ea-49ec-a218-62f865cce958/resource/0c08565c-9361-453b-ad46-900346b1d4d3/download/kankospot.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1861322,板橋区,A,35.75118,139.70927,東京都,板橋区,41.982445,keyword&Bbox,板橋区,2.0,3
1,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
2,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
3,11010196,浮間公園,L,35.79423,139.69273,東京都,板橋区,34.703102,Bbox,NaN,0.0,1
4,11010206,赤塚公園,L,35.78493,139.65645,東京都,板橋区,34.703102,Bbox,NaN,0.0,1
5,11010246,城北中央公園,L,35.75625,139.6731,東京都,練馬区,34.703102,Bbox,NaN,0.0,1
6,1864834,アズサワ,P,35.77658,139.70007,東京都,板橋区,28.919254,Bbox,NaN,0.0,1
7,8572884,へいわだい,P,35.75762,139.65984,東京都,練馬区,28.919254,Bbox,NaN,0.0,1
8,8572885,ヒカワダイ,P,35.75512,139.66758,東京都,練馬区,28.919254,Bbox,NaN,0.0,1
9,8572942,フナド,P,35.79406,139.68111,東京都,板橋区,28.919254,Bbox,NaN,0.0,1
10,8572943,しむら,P,35.77596,139.69037,東京都,板橋区,28.919254,Bbox,NaN,0.0,1
11,8572946,こもね,P,35.75131,139.6777,東京都,板橋区,28.919254,Bbox,NaN,0.0,1

==========================================
index:  12
[input information]
- title:  "131237_東京都_江戸川区_土のうステーション"
- notes:  "土のうステーションのデータです。
東京都江戸川区のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/9a5b7162-d849-4ab1-8b7d-068106d3c8b8/resource/d82920fe-bdc1-44ff-b236-966c3d1dedcf/download/20171101donou.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1864242,江戸川区,A,35.69242,139.87567,東京都,江戸川区,34.823803,keyword&Bbox,江戸川区,2.0,3
1,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
2,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
3,1849186,浦安市,P,35.67056,139.88861,東京都,,80.973907,Bbox,NaN,0.0,1
4,10918037,大島小松川公園,L,35.69286,139.85114,東京都,江戸川区,34.703102,Bbox,NaN,0.0,1
5,10918252,篠崎公園,L,35.70695,139.89705,東京都,江戸川区,34.703102,Bbox,NaN,0.0,1
6,10919509,篠崎公園,L,35.71561,139.89733,東京都,江戸川区,34.703102,Bbox,NaN,0.0,1
7,1862231,東立石,P,35.7336,139.84782,東京都,葛飾区,28.919254,Bbox,NaN,0.0,1
8,10919506,鹿骨,P,35.71146,139.8893,東京都,江戸川区,28.919254,Bbox,NaN,0.0,1
9,1852274,Shimo-komatsu,P,35.71667,139.86667,東京都,葛飾区,28.628599,Bbox,NaN,0.0,1
10,1855981,中川,H,35.66023,139.84977,,,23.135403,Bbox,NaN,0.0,1
11,1858906,小松川,P,35.7,139.85,東京都,江戸川区,23.135403,Bbox,NaN,0.0,1

==========================================
index:  13
[input information]
- title:  "092088_栃木県_小山市_公衆トイレ"
- notes:  "公衆トイレや公共トイレのデータです。
栃木県小山市のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/8517fadc-0e95-444d-8da8-07117facdb3c/resource/bb465e1c-1fcb-45df-b752-6b32402cfe8c/download/a930000h201401kosyutoire.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1853483,小山,P,36.3,139.8,栃木県,小山市,69.406204,keyword&Bbox,NaN,0.0,3
1,1853473,小山,A,36.308,139.80195,栃木県,小山市,46.270805,keyword&Bbox,NaN,0.0,3
2,1852901,篠山市,P,35.06667,135.21667,兵庫県,篠山市,51.238487,keyword,小山市,1.0,2
3,1850310,栃木県,A,36.7,139.81667,栃木県,,46.597225,keyword,栃木県,2.0,2
4,7370815,篠山,A,35.07523,135.23087,兵庫県,篠山市,45.451775,keyword,小山市,1.0,2
5,8572751,こやま,P,35.76549,139.52301,東京都,東久留米市,29.464870,keyword,小山,1.0,1
6,8550812,コヤマ,P,40.58531,141.22714,青森県,十和田市,29.464870,keyword,小山,1.0,1
7,8512317,コスギ,P,40.58035,140.53897,青森県,平川市,29.464870,keyword,小山,1.0,1
8,1853485,小山町,P,35.35693,138.99759,静岡県,駿東郡,28.335182,keyword,小山,1.0,1
9,1858619,小山,P,36.64457,138.31817,長野県,須坂市,27.094343,keyword,小山,1.0,1
10,1858620,小山,P,34.58162,135.59708,大阪府,藤井寺市,27.094343,keyword,小山,1.0,1
11,7551250,間々田駅,S,36.25791,139.76111,栃木県,小山市,23.135403,Bbox,NaN,0.0,1
12,1857709,Mamada,P,36.26667,139.76667,栃木県,小山市,17.351551,Bbox,NaN,0.0,1
13,7551233,おやまえき,S,36.31224,139.80641,栃木県,小山市,17.351551,Bbox,NaN,0.0,1
14,7424785,おやましやくしょ,S,36.31472,139.80028,栃木県,小山市,17.351551,Bbox,NaN,0.0,1
15,11836039,城山町,P,36.3164,139.80294,栃木県,小山市,11.567701,Bbox,NaN,0.0,1
16,11836062,天神町,P,36.30613,139.80042,栃木県,小山市,11.567701,Bbox,NaN,0.0,1
17,11836067,宮本町,P,36.31075,139.80241,栃木県,小山市,11.567701,Bbox,NaN,0.0,1
18,11836107,暁,P,36.25974,139.76419,栃木県,小山市,11.567701,Bbox,NaN,0.0,1

==========================================
index:  14
[input information]
- title:  "090000_栃木県_避難施設"
- notes:  "避難所、避難場所等のデータです。
栃木県のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/c2e3cfcb-8aba-47ba-b827-085db643fee9/resource/3e3e4c8e-035c-4544-afa0-e6d49f60b73b/download/226952015shitei-kinkyuhinan01043.csv


[Estimation Result]
Error: 緯度、経度の列がありません

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,1850311,栃木市,P,36.38333,139.73333,栃木県,栃木市,53.205894,keyword,栃木,1
1,1850310,栃木県,A,36.7,139.81667,栃木県,,46.597225,keyword,栃木県,1
2,7453590,栃木市,A,36.41128,139.69357,栃木県,栃木市,37.865883,keyword,栃木,1
3,2127795,トチギ,P,43.93227,143.71556,北海道,常呂郡,37.381741,keyword,栃木,1
4,11241617,トチノキ,P,32.7198,130.91495,熊本県,上益城郡,26.118805,keyword,栃木,1
5,11151176,栃木,P,32.86641,130.99553,熊本県,阿蘇郡,26.118805,keyword,栃木,1

==========================================
index:  15
[input information]
- title:  "114081_埼玉県_寄居町_観光地情報"
- notes:  "観光地情報のデータです。
埼玉県寄居町のオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/f4ec0705-065c-4ab6-8d8b-4a8105984801/resource/0f07ae48-c2c6-4771-91e7-561e9a041155/download/kankouti.csv


[Estimation Result]
Error: 緯度、経度の列がありません

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,1853226,埼玉県,A,35.85721,139.64904,埼玉県,,54.196476,keyword,埼玉県,2
1,7464134,寄居町,A,36.10493,139.19073,埼玉県,大里郡,25.196226,keyword,寄居町,2

==========================================
index:  16
[input information]
- title:  "高砂市ベストスポット2018"
- notes:  "2018年に高砂市役所が発表した、市民投票によるベストスポットの位置情報です。 推奨データセット及びNGSIに準じたオープンデータです。"
- filepath:  https://www.geospatial.jp/ckan/dataset/2dc3b2b5-a856-4845-8f59-c18b07dd08b2/resource/8e74fffc-e02f-4d01-bcf7-ee32fe00806b/download/takasagocitybestspot2018.csv


[Estimation Result]
Error: 緯度、経度の列がありません

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,1851005,高砂市,A,34.77796,134.78665,兵庫県,高砂市,38.745346,keyword,高砂市,2

==========================================
index:  17
[input information]
- title:  "37_香川県_雨量観測所"
- notes:  "雨量データを公表している雨量観測所の所在地一覧です"
- filepath:  nan


[Estimation Result]
File Not Found

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,1860834,香川県,A,34.24717,133.99471,香川県,,50.274933,keyword,香川県,1

==========================================
index:  18
[input information]
- title:  "避難所"
- notes:  "【品川区】　災害時等の避難所の位置情報"
- filepath:  http://www.city.shinagawa.tokyo.jp/ct/other000081500/hinansho.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1852140,品川区,A,35.60902,139.73017,東京都,品川区,46.588428,keyword&Bbox,品川区,1.0,2
1,1848649,山梨県,A,35.61667,138.6,山梨県,,69.406204,Bbox,NaN,0.0,1
2,1849407,上野原市,P,35.61667,139.11667,山梨県,上野原市,57.838509,Bbox,NaN,0.0,1
3,1853564,大月,P,35.61851,138.97396,山梨県,大月市,57.838509,Bbox,NaN,0.0,1
4,1858941,狛江市,A,35.63487,139.57723,東京都,狛江市,46.270805,Bbox,NaN,0.0,1
5,1849591,Tsuruga-gun,A,35.61667,136.08333,福井県,Tsuruga-gun,46.270805,Bbox,NaN,0.0,1
6,1850731,多摩市,A,35.63054,139.43976,東京都,多摩市,46.270805,Bbox,NaN,0.0,1
7,1852141,Ebara-ku,A,35.6,139.71667,東京都,,46.270805,Bbox,NaN,0.0,1
8,1861634,稲城市,A,35.6329,139.49291,東京都,稲城市,46.270805,Bbox,NaN,0.0,1
9,7412200,京丹後市,A,35.63089,135.04785,京都府,京丹後市,46.270805,Bbox,NaN,0.0,1

==========================================
index:  19
[input information]
- title:  "区内の橋梁一覧"
- notes:  "区内の橋梁の名称や読み方、所在地、緯度、経度、管理者、橋下状況などを掲載しています。"
- filepath:  https://www.city.chuo.lg.jp/kusei/statisticaldata/opendata.files/kyoryo.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,10475437,橋下,P,35.15335,138.63797,静岡県,富士市,19.674904,keyword,橋下,1.0,1
1,1863623,銀座,P,35.67184,139.76717,東京都,中央区,46.270805,Bbox,NaN,0.0,1
2,1864487,中央区,A,35.66993,139.77705,東京都,中央区,46.270805,Bbox,NaN,0.0,1
3,1860235,Kanda,L,35.69097,139.77062,,,46.270805,Bbox,NaN,0.0,1
4,1855459,日本橋,L,35.68154,139.77404,東京都,中央区,40.897999,Bbox,NaN,0.0,1
5,1849687,月島,P,35.66259,139.78195,東京都,中央区,40.486954,Bbox,NaN,0.0,1
6,1856401,日本橋室町,P,35.68805,139.7726,東京都,中央区,34.703102,Bbox,NaN,0.0,1
7,1857654,丸の内,P,35.68146,139.76328,東京都,千代田区,34.703102,Bbox,NaN,0.0,1
8,1849668,佃,P,35.6679,139.78481,東京都,中央区,34.703102,Bbox,NaN,0.0,1
9,1849693,築地,P,35.66487,139.77004,東京都,中央区,34.703102,Bbox,NaN,0.0,1
10,1855455,日本橋箱崎町,P,35.67951,139.78619,東京都,中央区,34.703102,Bbox,NaN,0.0,1

==========================================
index:  20
[input information]
- title:  "東京都内のスポーツ施設一覧"
- notes:  "【東京都オリンピック・パラリンピック準備局】"
- filepath:  http://www.opendata.metro.tokyo.jp/2018appcon/olympic/130001sports_facilities.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1850147,東京,P,35.6895,139.69171,東京都,,231.354034,keyword&Bbox,NaN,0.0,3
1,1850144,東京都,A,35.6895,139.69171,東京都,,92.541611,keyword&Bbox,NaN,0.0,3
2,8742958,冬井,P,37.23731,138.82041,新潟県,小千谷市,28.009701,keyword,東京,1.0,1
3,1861060,日本,A,35.68536,139.75309,,,161.947815,Bbox,NaN,0.0,1
4,1856367,武蔵野,P,35.70611,139.55944,東京都,武蔵野市,80.973907,Bbox,NaN,0.0,1
5,1858964,国分寺,P,35.70222,139.47556,東京都,国分寺市,69.406204,Bbox,NaN,0.0,1
6,1860437,上連雀,P,35.69423,139.55495,東京都,三鷹,69.406204,Bbox,NaN,0.0,1
7,7279570,東村山市,P,35.75459,139.46852,東京都,東村山市,69.406204,Bbox,NaN,0.0,1
8,1850692,西東京市,P,35.72526,139.5383,東京都,西東京市,65.436798,Bbox,NaN,0.0,1
9,1850693,田無町,P,35.72922,139.53813,東京都,西東京市,57.838509,Bbox,NaN,0.0,1
10,1864518,調布ヶ丘,P,35.65924,139.54837,東京都,調布市,57.838509,Bbox,NaN,0.0,1

==========================================
index:  21
[input information]
- title:  "【位置情報】公衆無線LANアクセスポイント一覧"
- notes:  "公衆無線LANアクセスポイントの一覧データです。"
- filepath:  https://www.city.mitaka.lg.jp/c_service/085/attached/attach_85844_2.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod
0,8572826,いのかしらこうえん,L,35.70018,139.57413,東京都,武蔵野市,40.486954,Bbox
1,7552117,キチジョウジエキ,S,35.70229,139.58031,東京都,武蔵野市,23.135403,Bbox
2,7552127,井の頭公園駅,S,35.69729,139.58312,東京都,三鷹,23.135403,Bbox
3,10876098,吉祥寺南町,P,35.70056,139.5851,東京都,武蔵野市,23.135403,Bbox
4,10867078,井の頭,P,35.69313,139.5834,東京都,三鷹,17.351551,Bbox
5,10875920,井の頭自然文化園,S,35.70077,139.57119,東京都,武蔵野市,11.567701,Bbox
6,6471863,Kichijoji Tokyu Inn,S,35.7002,139.5827,東京都,武蔵野市,5.783851,Bbox

==========================================
index:  22
[input information]
- title:  "観光施設一覧"
- notes:  "【西東京市】西東京市内の観光施設の一覧です。内閣官房情報通信技術（IT）総合戦略室が平成29年12月22日に公開した、推奨データセットに準拠して作成しています。"
- filepath:  http://www.city.nishitokyo.lg.jp/opendata/132292_tourism.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1850692,西東京市,P,35.72526,139.5383,東京都,西東京市,65.436798,keyword&Bbox,NaN,0.0,3
1,8304376,西東京市,A,35.73485,139.54624,東京都,西東京市,46.270805,keyword&Bbox,NaN,0.0,3
2,11611931,西東京,P,35.73355,139.54761,東京都,西東京市,28.919254,keyword&Bbox,NaN,0.0,2
3,11209892,平成,P,32.77889,130.70291,熊本県,熊本市,31.305401,keyword,平成,1.0,1
4,11811630,平成,P,37.30867,138.79359,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
5,11811631,平成,P,37.31833,138.78947,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
6,11839322,平成,P,38.27169,140.91631,宮城県,仙台市,16.343479,keyword,平成,1.0,1
7,1850693,田無町,P,35.72922,139.53813,東京都,西東京市,57.838509,Bbox,NaN,0.0,1
8,1862071,保谷市,A,35.7415,139.55881,東京都,保谷市,46.270805,Bbox,NaN,0.0,1
9,8572749,ミナミサワ,P,35.74872,139.52847,東京都,東久留米市,28.919254,Bbox,NaN,0.0,1
10,8572758,東伏見,P,35.72525,139.56031,東京都,西東京市,28.919254,Bbox,NaN,0.0,1
11,1907304,柳沢,P,35.72421,139.55205,東京都,西東京市,23.135403,Bbox,NaN,0.0,1
12,7551995,ひばりがおかえき,S,35.75144,139.54576,東京都,西東京市,23.135403,Bbox,NaN,0.0,1
13,7552008,タナシエキ,S,35.7272,139.53898,東京都,西東京市,23.135403,Bbox,NaN,0.0,1

==========================================
index:  23
[input information]
- title:  "文化財一覧"
- notes:  "【東京都教育庁】東京都指定文化財の一覧です。現在は、一般公開されており、所有者・管理者の承諾が得られたもののみを公開しています。内閣官房情報通信技術（IT）総合戦略室が平成29年12月22日に公開した、推奨データセットに準拠して作成しています。"
- filepath:  http://www.opendata.metro.tokyo.jp/suisyoudataset/130001_cultural_property.csv


[Estimation Result]
geonames query result has an error:
{'status': {'message': 'missing or invalid parameter for south/north/east/west', 'value': 14}}

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1850147.0,東京,P,35.6895,139.69171,東京都,,153.311920,keyword,東京都,2.0,2
1,1850144.0,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,2.0,2
2,11710429.0,ぶんか,P,43.09699,143.22329,北海道,河東郡,24.811647,keyword,文化,2.0,2
3,11790371.0,文花,P,35.70946,139.821,東京都,墨田区,19.400734,keyword,文化,2.0,2
4,10922476.0,文化,H,35.70927,139.82379,東京都,,13.989820,keyword,文化,2.0,2
5,11209892.0,平成,P,32.77889,130.70291,熊本県,熊本市,31.305401,keyword,平成,1.0,1
6,11811630.0,平成,P,37.30867,138.79359,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
7,11811631.0,平成,P,37.31833,138.78947,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
8,11839322.0,平成,P,38.27169,140.91631,宮城県,仙台市,16.343479,keyword,平成,1.0,1

==========================================
index:  24
[input information]
- title:  "東京都イベント一覧"
- notes:  "【東京都総務局】東京都が主催者等であるイベント情報の一覧です。 内閣官房情報通信技術（IT）総合戦略室が平成29年12月22日に公開した、推奨データセットに準拠して作成しています。"
- filepath:  http://www.opendata.metro.tokyo.jp/suisyoudataset/130001_event.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1850147,東京,P,35.6895,139.69171,東京都,,153.311920,keyword&Bbox,東京都,3.0,4
1,1850144,東京都,A,35.6895,139.69171,東京都,,69.262291,keyword,東京都,3.0,3
2,11209892,平成,P,32.77889,130.70291,熊本県,熊本市,31.305401,keyword,平成,1.0,1
3,11811630,平成,P,37.30867,138.79359,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
4,11811631,平成,P,37.31833,138.78947,新潟県,小千谷市,16.343479,keyword,平成,1.0,1
5,11839322,平成,P,38.27169,140.91631,宮城県,仙台市,16.343479,keyword,平成,1.0,1
6,1862185,本州,T,36,138,,,185.083221,Bbox,NaN,0.0,1
7,1864496,中部地方,L,36,137.5,,,161.947815,Bbox,NaN,0.0,1
8,1860102,関東地方,L,36.25,139.5,,,161.947815,Bbox,NaN,0.0,1
9,1861060,日本,A,35.68536,139.75309,,,161.947815,Bbox,NaN,0.0,1
10,6940394,さいたま,P,35.90807,139.65657,埼玉県,さいたま市,138.812408,Bbox,NaN,0.0,1
11,1855431,ニイガタシ,P,37.88637,139.00589,新潟県,新潟市,115.677017,Bbox,NaN,0.0,1
12,1856215,長野市,P,36.65,138.18333,長野県,長野市,92.541611,Bbox,NaN,0.0,1
13,1857843,前橋市,P,36.4,139.08333,群馬県,前橋市,92.541611,Bbox,NaN,0.0,1
14,1859100,コウフシ,P,35.66667,138.56667,山梨県,甲府市,92.541611,Bbox,NaN,0.0,1

==========================================
index:  25
[input information]
- title:  "福岡市　避難場所・避難所（共通フォーマット）"
- notes:  "福岡市の避難場所・避難所を，福岡市，北九州市，久留米市の３市で共通化したフォーマットにしたデータです。"
- filepath:  https://ckan.open-governmentdata.org/dataset/b299cddc-0a54-4aae-a32c-9e14ba0d0aae/resource/9197f659-de3a-46a3-b063-430f2e73d5eb/download/401307compatibleformatshelter.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1863967,福岡市,P,33.6,130.41667,福岡県,福岡市,118.477837,keyword&Bbox,福岡市,2.0,4
1,1863955,福岡市,A,33.56894,130.35764,福岡県,福岡市,38.089046,keyword&Bbox,福岡市,2.0,4
2,1850091,富岡,P,36.25411,138.89813,群馬県,富岡市,56.444725,keyword,福岡市,2.0,3
3,1850090,富岡市,A,36.25,138.88333,群馬県,富岡市,41.770409,keyword,福岡市,2.0,3
4,1859307,北九州市,P,33.85181,130.85034,福岡県,北九州市,84.523781,keyword,北九州市,1.0,1
5,1858088,久留米市,P,33.31667,130.51667,福岡県,久留米市,53.927597,keyword,久留米,1.0,1
6,1863958,福岡県,A,33.52813,130.66472,福岡県,,39.684731,keyword,福岡,1.0,1
7,1859306,きたきゅうしゅうし,A,33.85181,130.84659,福岡県,北九州市,38.446518,keyword,北九州市,1.0,1
8,1858087,くるめし,A,33.30358,130.56549,福岡県,久留米市,38.446518,keyword,久留米,1.0,1
9,1850093,富岡,P,32.51857,130.0359,熊本県,天草郡,35.472527,keyword,福岡,1.0,1
10,2130326,福岡,P,40.27857,141.32318,岩手県,二戸市,30.081446,keyword,福岡,1.0,1
11,1863963,フクオカ,P,35.87773,139.54678,埼玉県,ふじみ野市,30.081446,keyword,福岡,1.0,1
12,8476725,ふくおか,P,40.797,140.49498,青森県,五所川原市,30.081446,keyword,福岡,1.0,1
13,8477067,富岡,P,40.79636,140.38041,青森県,つがる市,30.081446,keyword,福岡,1.0,1
14,6822146,大野城市,P,33.53567,130.47861,福岡県,大野城市,69.406204,Bbox,NaN,0.0,1
15,6300346,福岡空港,S,33.58594,130.45069,福岡県,福岡市,69.406204,Bbox,NaN,0.0,1
16,1857844,前原中央,P,33.55916,130.20148,福岡県,糸島市,57.838509,Bbox,NaN,0.0,1
17,1859094,古賀,P,33.73333,130.46667,福岡県,古賀市,46.270805,Bbox,NaN,0.0,1
18,1852109,新宮,P,33.71399,130.4313,福岡県,糟屋郡,46.270805,Bbox,NaN,0.0,1
19,1854000,大野城市,A,33.51302,130.47925,福岡県,大野城市,46.270805,Bbox,NaN,0.0,1
20,1863978,西福間,P,33.76627,130.47461,福岡県,福津市,46.270805,Bbox,NaN,0.0,1
21,1864574,ちくしぐん,A,33.46626,130.42202,福岡県,筑紫郡,46.270805,Bbox,NaN,0.0,1

==========================================
index:  26
[input information]
- title:  "北九州市　避難場所・避難所（共通フォーマット）"
- notes:  "北九州市の避難場所・避難所を、北九州市、福岡市、久留米市の３市で共通化したフォーマットにしたデータです。"
- filepath:  https://ckan.open-governmentdata.org/dataset/03ea03e1-6c34-4203-86a1-1c4a32fc4b91/resource/62eeb4c2-409d-4ee6-b18e-2eda2a6e7ef4/download/401005_hinanbasyo_20200701.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,1859307,北九州市,P,33.85181,130.85034,福岡県,北九州市,84.523781,keyword&Bbox,北九州市,2.0,4
1,1859306,きたきゅうしゅうし,A,33.85181,130.84659,福岡県,北九州市,38.446518,keyword&Bbox,北九州市,2.0,4
2,1863967,福岡市,P,33.6,130.41667,福岡県,福岡市,118.477837,keyword,福岡市,1.0,1
3,1850091,富岡,P,36.25411,138.89813,群馬県,富岡市,56.444725,keyword,福岡市,1.0,1
4,1858088,久留米市,P,33.31667,130.51667,福岡県,久留米市,53.927597,keyword,久留米,1.0,1
5,1850090,富岡市,A,36.25,138.88333,群馬県,富岡市,41.770409,keyword,福岡市,1.0,1
6,1858087,くるめし,A,33.30358,130.56549,福岡県,久留米市,38.446518,keyword,久留米,1.0,1
7,1863955,福岡市,A,33.56894,130.35764,福岡県,福岡市,38.089046,keyword,福岡市,1.0,1
8,1852225,下関市,P,33.95,130.95,山口県,,80.973907,Bbox,NaN,0.0,1
9,1855907,中間市,P,33.81688,130.70962,福岡県,中間市,57.838509,Bbox,NaN,0.0,1
10,1855902,中間,A,33.82081,130.70862,福岡県,中間市,46.270805,Bbox,NaN,0.0,1
11,1858305,鞍手郡,A,33.76136,130.68015,福岡県,鞍手郡,46.270805,Bbox,NaN,0.0,1
12,1860234,Kanda,P,33.78333,130.98333,福岡県,京都郡,46.270805,Bbox,NaN,0.0,1
13,7407417,直方市,A,33.75116,130.74592,福岡県,直方市,46.270805,Bbox,NaN,0.0,1
14,10316904,スペースワールド,L,33.87312,130.81102,福岡県,北九州市,46.270805,Bbox,NaN,0.0,1
15,1856343,六連島,T,33.97554,130.86393,山口県,,40.486954,Bbox,NaN,0.0,1

==========================================
index:  27
[input information]
- title:  "農産物直売所"
- notes:  "市内のファーマーズマーケット開催情報です。データ形式 lodでも公開しています。http://data.odp.jig.jp/rdf/jp/shizuoka/shimada/661.rdf"
- filepath:  https://ckan.pref.shizuoka.jp/dataset/35fea25e-3465-4545-b777-9aac251249d1/resource/c14cb22e-7615-48e8-b0e7-ed5fb3a5cbf3/download/farmersmarket.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount,freqAppearance
0,9815255,産物,P,40.21707,140.09716,秋田県,能代市,31.137297,keyword,産物,1.0,1
1,1852472,島田,P,34.81667,138.18333,静岡県,島田市,69.406204,Bbox,NaN,0.0,1
2,1860256,金谷,P,34.82022,138.12775,静岡県,島田市,46.270805,Bbox,NaN,0.0,1
3,7418322,島田市,A,34.9122,138.12662,静岡県,島田市,46.270805,Bbox,NaN,0.0,1
4,1864695,菩提山,T,34.94164,138.16026,静岡県,藤枝市,34.703102,Bbox,NaN,0.0,1
5,8659818,栗島,P,34.86587,138.07547,静岡県,島田市,28.919254,Bbox,NaN,0.0,1
6,1857736,牧の原,P,34.81667,138.11667,静岡県,島田市,23.135403,Bbox,NaN,0.0,1
7,1858337,久野脇,P,35,138.08333,静岡県,榛原郡,23.135403,Bbox,NaN,0.0,1
8,1855112,日坂,P,34.81604,138.08168,静岡県,かけがわし,23.135403,Bbox,NaN,0.0,1
9,1865753,阿知ヶ谷,P,34.84073,138.20128,静岡県,島田市,23.135403,Bbox,NaN,0.0,1
10,8659734,下志戸呂,P,34.83533,138.11814,静岡県,島田市,23.135403,Bbox,NaN,0.0,1

==========================================
index:  28
[input information]
- title:  "パブリックタグ情報"
- notes:  "国土地理院に登録されたWi-Fiやビーコンなど位置特定に利用可能な機器の設置位置などの属性に関する情報"
- filepath:  https://ucopendb.gsi.go.jp/ucode/ptisi_opendata.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod
0,1850147,東京,P,35.6895,139.69171,東京都,,231.354034,Bbox
1,1860102,関東地方,L,36.25,139.5,,,161.947815,Bbox
2,1861060,日本,A,35.68536,139.75309,,,161.947815,Bbox
3,1859642,川崎,P,35.52056,139.71722,神奈川県,川崎市,138.812408,Bbox
4,6940394,さいたま,P,35.90807,139.65657,埼玉県,さいたま市,138.812408,Bbox
5,2113015,千葉市,P,35.6,140.11667,千葉県,千葉市,115.677017,Bbox
6,1857843,前橋市,P,36.4,139.08333,群馬県,前橋市,92.541611,Bbox
7,1859100,コウフシ,P,35.66667,138.56667,山梨県,甲府市,92.541611,Bbox
8,1849053,ウツノミヤシ,P,36.56667,139.88333,栃木県,宇都宮市,92.541611,Bbox
9,1850144,東京都,A,35.6895,139.69171,東京都,,92.541611,Bbox

==========================================
index:  29
[input information]
- title:  "気象予報_天気予報・台風の資料"
- notes:  "過去の天気図や台風資料、予報の精度検証結果などの天気予報・台風の分析・統計資料"
- filepath:  https://www.data.jma.go.jp/fcd/yoho/typhoon/position_table/table2019.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod
0,1850147,東京,P,35.6895,139.69171,東京都,,231.354034,Bbox
1,2128295,札幌市,P,43.06667,141.35,北海道,札幌市,185.083221,Bbox
2,1856057,名古屋,P,35.18147,136.90641,愛知県,名古屋市,185.083221,Bbox
3,1859171,神戸市,P,34.6913,135.183,兵庫県,神戸市,185.083221,Bbox
4,1848354,横浜市,P,35.43333,139.65,神奈川県,横浜市,185.083221,Bbox
5,1853909,大阪市,P,34.69374,135.50218,大阪府,大阪市,185.083221,Bbox
6,1862185,本州,T,36,138,,,185.083221,Bbox
7,1857891,キュウシュウチホウ,L,32.33546,130.85082,,,161.947815,Bbox
8,1857892,キュウシュウ,T,32.42944,130.99099,熊本県,,161.947815,Bbox
9,1857910,京都市,P,35.02107,135.75385,京都府,京都市,161.947815,Bbox

==========================================
index:  30
[input information]
- title:  nan
- notes:  nan
- filepath:  https://koukita.github.io/hokkaido_od_geodatabase/data/Hokkaido_OD_GeoDataBase2018.csv


[Estimation Result]

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod
0,2128295,札幌市,P,43.06667,141.35,北海道,札幌市,185.083221,Bbox
1,11257417,北海道,L,43.51669,142.44873,北海道,空知郡,138.812408,Bbox
2,2130038,ホッカイドウ,T,44,143,北海道,,115.677017,Bbox
3,2130188,函館,P,41.77583,140.73667,北海道,函館市,92.541611,Bbox
4,2130037,北海道,A,43.06451,141.3466,北海道,,92.541611,Bbox
5,2130629,旭川,P,43.77063,142.36489,北海道,旭川市,80.973907,Bbox
6,2128574,小樽,P,43.18944,141.00222,北海道,小樽市,80.973907,Bbox
7,2129376,釧路,P,42.975,144.37472,北海道,釧路市,80.973907,Bbox
8,2129537,北見市,P,43.80306,143.89083,北海道,北見市,80.973907,Bbox
9,2130404,江別市,P,43.10806,141.55056,北海道,江別市,69.406204,Bbox

==========================================
index:  31
[input information]
- title:  国分寺市にある避難所の位置情報データ
- notes:  国分寺市にある避難所の位置情報データ
- filepath:  nan


[Estimation Result]
File Not Found

,geonameId,name,fcl,lat,lng,adminName1,adminName2,score,searchMethod,searchKeyword,searchKeywordCount
0,1858964,国分寺,P,35.70222,139.47556,東京都,国分寺市,69.590363,keyword,国分寺市,2
1,1858962,国分寺市,A,35.70552,139.46125,東京都,国分寺市,38.446518,keyword,国分寺市,2